### ISSUE TITLE
evilProgram_flat.csv

### ISSUE THREAD

**Issue by ankurmitujjain** [ResearchTriangleAnalysts/CyberSecurity#2]
Hi ,
Can you please share evilProgram_flat.csv
Thanks

**Comment by eoyount** [comment]
Omar - do you have a copy of this file? I looked on http://www.netresec.com/?page=PcapFiles but I didn't see a file with that name. Thanks!

**Comment by ankurmitujjain** [comment]
@santosomar do u have the copy?

**Comment by eoyount** [comment]
Found it. Uploaded to data directory.

**Comment by ankurmitujjain** [comment]
Thanks @eoyount

**Comment by vishrtd** [comment]
Hello, I tried reproducing the example. But the ggplot looks all mess. I am getting a warning 

> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

which I tried resetting with different values, which are ignored by RStudio.

> Warning message:
> In GGally::ggpairs(evilprog, columns = 2:6, title = "Scatter Plot",  :
>   Extra arguments: "stat_bin" are being ignored.  If these are meant to be aesthetics, submit them using the 'mapping' variable within ggpairs with ggplot2::aes or ggplot2::aes_string.
